# Generated by Django 4.2.7 on 2024-02-03 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='buildings',
            field=models.ManyToManyField(related_name='city', to='builder.building'),
        ),
        migrations.AddField(
            model_name='city',
            name='fire_departments',
            field=models.ManyToManyField(related_name='city', to='builder.firedepartment'),
        ),
        migrations.AddField(
            model_name='city',
            name='hospitals',
            field=models.ManyToManyField(related_name='city', to='builder.hospital'),
        ),
        migrations.AddField(
            model_name='city',
            name='police_stations',
            field=models.ManyToManyField(related_name='city', to='builder.policestation'),
        ),
        migrations.AddField(
            model_name='city',
            name='schools',
            field=models.ManyToManyField(related_name='city', to='builder.school'),
        ),
        migrations.AddField(
            model_name='city',
            name='transports',
            field=models.ManyToManyField(related_name='city', to='builder.transport'),
        ),
        migrations.AddField(
            model_name='city',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='firedepartment',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospital',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policestation',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transport',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
